//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CitesDataProcessing
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ISDataBaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ISDataBaseEntities object using the connection string found in the 'ISDataBaseEntities' section of the application configuration file.
        /// </summary>
        public ISDataBaseEntities() : base("name=ISDataBaseEntities", "ISDataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ISDataBaseEntities object.
        /// </summary>
        public ISDataBaseEntities(string connectionString) : base(connectionString, "ISDataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ISDataBaseEntities object.
        /// </summary>
        public ISDataBaseEntities(EntityConnection connection) : base(connection, "ISDataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Catalog> Catalogs
        {
            get
            {
                if ((_Catalogs == null))
                {
                    _Catalogs = base.CreateObjectSet<Catalog>("Catalogs");
                }
                return _Catalogs;
            }
        }
        private ObjectSet<Catalog> _Catalogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductCatalog> ProductCatalogs
        {
            get
            {
                if ((_ProductCatalogs == null))
                {
                    _ProductCatalogs = base.CreateObjectSet<ProductCatalog>("ProductCatalogs");
                }
                return _ProductCatalogs;
            }
        }
        private ObjectSet<ProductCatalog> _ProductCatalogs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Catalogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCatalogs(Catalog catalog)
        {
            base.AddObject("Catalogs", catalog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductCatalogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductCatalogs(ProductCatalog productCatalog)
        {
            base.AddObject("ProductCatalogs", productCatalog);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISDataBaseModel", Name="Catalog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Catalog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Catalog object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="fatherID">Initial value of the FatherID property.</param>
        public static Catalog CreateCatalog(global::System.Int32 id, global::System.String name, global::System.Int32 fatherID)
        {
            Catalog catalog = new Catalog();
            catalog.ID = id;
            catalog.Name = name;
            catalog.FatherID = fatherID;
            return catalog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FatherID
        {
            get
            {
                return _FatherID;
            }
            set
            {
                if (_FatherID != value)
                {
                    OnFatherIDChanging(value);
                    ReportPropertyChanging("FatherID");
                    _FatherID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FatherID");
                    OnFatherIDChanged();
                }
            }
        }
        private global::System.Int32 _FatherID;
        partial void OnFatherIDChanging(global::System.Int32 value);
        partial void OnFatherIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISDataBaseModel", Name="ProductCatalog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductCatalog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductCatalog object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="fatherID">Initial value of the FatherID property.</param>
        public static ProductCatalog CreateProductCatalog(global::System.Int32 id, global::System.String name, global::System.Int32 fatherID)
        {
            ProductCatalog productCatalog = new ProductCatalog();
            productCatalog.ID = id;
            productCatalog.Name = name;
            productCatalog.FatherID = fatherID;
            return productCatalog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FatherID
        {
            get
            {
                return _FatherID;
            }
            set
            {
                OnFatherIDChanging(value);
                ReportPropertyChanging("FatherID");
                _FatherID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FatherID");
                OnFatherIDChanged();
            }
        }
        private global::System.Int32 _FatherID;
        partial void OnFatherIDChanging(global::System.Int32 value);
        partial void OnFatherIDChanged();

        #endregion
    
    }

    #endregion
    
}
